### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by LucidNyxx** [zuzumi-f/Twiter-Theme-BD#1]
Awesome theme! But is there a way to remove that blue glow around everything when it's popped out?

**Comment by zuzumi-f** [comment]
yeah, you can put this code in below the @import and change the var(tw.No.)

:root {
    --tw1: hsl(210, 34%, 13%);
    --tw2: hsl(203, 89%, 53%);
    --tw3: hsla(206, 16%, 26%, 0.69);
}
:root {
    --elevation-stroke: 0 0 0 1px var(--tw1);
    --elevation-low: 0 1px 0 var(--tw1),0 1.5px 0 var(--tw1),0 2px 0 var(--tw1);
    --elevation-medium: 0 4px 4px var(--tw1);
    --elevation-high: 0 8px 16px var(--tw1);
    --guild-header-text-shadow: 0 1px 1px var(--tw1);
}
